{
 "title": "Nginx Proxy Manager",
 "description": "Loki v2+ showcase using JSON NGINX access logs.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Services",
    "query": "radarr : /media/npm/proxy_hostjson-radarr.log,deluge : /media/npm/proxy_hostjson-deluge.log,authelia : /media/npm/proxy_hostjson-authelia.log,sonarr : /media/npm/proxy_hostjson-sonarr.log,phpmyadmin : /media/npm/proxy_hostjson-phpmyadmin.log,tautulli : /media/npm/proxy_hostjson-tautulli.log, overseerr : /media/npm/proxy_hostjson-overseerr.log,bitwarden : /media/npm/proxy_hostjson-bitwarden.log,jackett : /media/npm/proxy_hostjson-jackett.log,status : /media/npm/proxy_hostjson-status.log,guacamole : /media/npm/proxy_hostjson-guacamole.log,mkvtoolnix : /media/npm/proxy_hostjson-mkvtoolnix.log,portainer : /media/npm/proxy_hostjson-portainer.log,firefly : /media/npm/proxy_hostjson-firefly.log,element : /media/npm/proxy_hostjson-element.log,matrix : /media/npm/proxy_hostjson-matrix.log,photoprism : /media/npm/proxy_hostjson-photoprism.log,joplin : /media/npm/proxy_hostjson-joplin.log"
   }
  ]
 },
 "panels": [
  { "title": "KPI's", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({filename=~\"$Services\"} | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status: {{status}}"
    }
   ]
  },
  {
   "title": "% of 1xx requests ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=\"$Services\"} | json | status >= 100 and status < 200 [$__interval])) / (sum(count_over_time({filename=\"$Services\"} | json [$__interval]))/ 100)"
    }
   ]
  },
  {
   "title": "% of 2xx requests ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=~\"$Services\"} | json | status = 200 or status < 300 [$__interval])) / (sum(count_over_time({filename=~\"$Services\"} | json [$__interval]))/ 100)"
    }
   ]
  },
  {
   "title": "% of 3xx requests ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=~\"$Services\"} | json | status >= 300 and status < 400 |__error__=\"\"[$__interval])) / (sum(count_over_time({filename=~\"$Services\"} | json | __error__=\"\"[$__interval]))/ 100)"
    }
   ]
  },
  {
   "title": "% of 4xx requests ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=~\"$Services\"} | json | status >= 400 |__error__=\"\"[$__interval])) / (sum(count_over_time({filename=~\"$Services\"} | json | __error__=\"\"[$__interval]))/ 100)"
    }
   ]
  },
  {
   "title": "% of 5xx requests ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=~\"$Services\"} | json | status >= 500 |__error__=\"\"[$__interval])) / (sum(count_over_time({filename=~\"$Services\"} | json | __error__=\"\"[$__interval]))/ 100)"
    }
   ]
  },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({filename=~\"$Services\",job=\"npm\"}[$__interval]))  "
    }
   ]
  },
  {
   "title": "# NGINX log lines queried for this period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({filename=~\"$Services\"}[$__interval]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "NGINX logs queried ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(bytes_over_time({filename=~\"$Services\"}[4w]))"
    }
   ]
  },
  {
   "title": "Unique users ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({filename=~\"$Services\"} | json |  __error__=\"\" [$__interval])))"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({filename=~\"$Services\"} | json | unwrap body_bytes_sent |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "%  by Googlebot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": " sum(count_over_time(({filename=\"$Services\"} |= \"Googlebot\")[$__interval])) / (sum(count_over_time(({filename=\"$Services\"} != \"Googlebot\")[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": "Public ip address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.public_ip" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Location",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 20, "x": 0, "y": 13 },
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by(geoip_country_code) (count_over_time({filename=~\"$Services\"} | __error__=`` | json [$__interval]))"
    }
   ]
  },
  {
   "title": "Top Countries",
   "type": "table",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 13 },
   "targets": [
    {
     "expr": "topk(15, sum by (geoip_country_code) (count_over_time({filename=~\"$Services\"} | json | geoip_country_code != \"\" and  __error__=\"\" [$__interval])))",
     "legendFormat": "{{geoip_country_code}}"
    }
   ]
  },
  {
   "title": "Recent requests",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{filename=~\"$Services\"} | json | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | remote_addr !~ \"2001:4ca0:108:42::*\" | remote_addr !=\"62.210.149.41\" | remote_addr !~ \"91.134.156.*\" | remote_addr !~ \"37.59.149.*\" | http_user_agent != \"worldping-api\" | request_uri !~ \"/wp-.*\" | request_uri !~ \"//wp-.*\" | request_uri !~ \"/*.wordfence.*\" | request_uri !~ \"/robots.txt\" | request_uri !~ \"/xmlrpc.php\" | line_format \"{{.date}} {{.time}} ({{.status}}) in {{.geoip_country_name}} - {{.geoip_city_code}} {{.remote_addr}} {{.http_host}}{{.request_uri}}\""
    }
   ]
  },
  {
   "title": "HTTP status codes over time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({filename=~\"$Services\"} | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status {{status}}"
    }
   ]
  },
  {
   "title": "Websites",
   "type": "graph",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (http_host)(count_over_time({filename=~\"$Services\", host=\"srv1\"} | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "{{http_host}}"
    }
   ]
  },
  { "title": "Visitor Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Unique user visits",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(sum by (remote_addr) (count_over_time({filename=~\"$Services\"} | json | http_user_agent !~ \".*bot.*\" | http_user_agent !~ \".*crawler.*\" | remote_addr !~ \"2001:4ca0:108:42::*\" | remote_addr !=\"62.210.149.41\" | remote_addr !~ \"91.134.156.*\" | remote_addr !~ \"37.59.149.*\" | http_user_agent != \"worldping-api\" | request_uri !~ \"/wp-.*\" | request_uri !~ \"//wp-.*\" | request_uri !~ \"/*.wordfence.*\" | request_uri !~ \"/robots.txt\" | request_uri !~ \"/xmlrpc.php\" |  __error__=\"\" [$__interval])))",
     "legendFormat": "Unique user visit count"
    }
   ]
  },
  { "title": "Request statistics over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "95th percentile of Request Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{filename=~\"$Services\"} | json | unwrap request_time |  __error__=\"\"  [$__interval]) by (host)",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "max by (host) (max_over_time({filename=~\"$Services\", host=\"$host\"} | json | unwrap request_time |  __error__=\"\"  [$__interval]))",
     "legendFormat": "max latency"
    }
   ]
  },
  {
   "title": "HTTP status codes over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({filename=~\"$Services\"} | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "HTTP Status {{status}}"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 61 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (host) (sum_over_time({filename=~\"$Services\"} | json | status=200 | unwrap body_bytes_sent |  __error__=\"\" [$__interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  { "title": "Acquisition and Behaviour", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Top User Agents",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "topk(100, sum by (http_user_agent) (count_over_time({filename=~\"$Services\"} | json |  __error__=\"\" [$__interval])))",
     "legendFormat": "{{http_user_agent}}"
    }
   ]
  },
  {
   "title": "Top IPs",
   "type": "table",
   "gridPos": { "h": 38, "w": 11, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "topk(100, sum by (remote_addr) (count_over_time({filename=~\"$Services\"} | json  |  __error__=\"\" [$__interval])))",
     "legendFormat": "{{http_x_forwarded_for}}"
    }
   ]
  },
  {
   "title": "Top Requested Pages",
   "type": "table",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 77 },
   "targets": [
    {
     "expr": "topk(300, sum by (request_uri) (count_over_time({filename=~\"$Services\"} !~ `\\.ico|\\.svg|\\.css|\\.png|\\.txt|\\.js|\\.xml` | json | status = 200 and request_uri != \"/\" | __error__=\"\" [$__interval])))",
     "legendFormat": "{{request_uri}}"
    }
   ]
  },
  {
   "title": "Top websites",
   "type": "table",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 89 },
   "targets": [
    {
     "expr": "topk(100, sum by (http_host) (count_over_time({filename=~\"$Services\"} | json |  __error__=\"\" [$__interval])))",
     "legendFormat": "{{http_host}}"
    }
   ]
  },
  {
   "title": "Top HTTP Referers",
   "type": "table",
   "gridPos": { "h": 15, "w": 13, "x": 11, "y": 100 },
   "targets": [
    {
     "expr": "topk(100, sum by (http_referer) (count_over_time({filename=~\"$Services\"} | json |  http_referer != \"\" and http_referer !~ \".*?$host.*?\" and http_referer !~ \".*?\\\\*\\\\*\\\\*.*?\" | __error__=\"\" [$__interval])))",
     "legendFormat": "{{http_referer}}"
    }
   ]
  }
 ]
}